import type { NextPage } from 'next'
import Head from 'next/head'
import { ActionItems } from '../components/ActionItems/ActionItems';
import { Map } from '../components/Map/Map';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-700 text-white w-full min-h-screen">
        <div className="w-full grid grid-cols-1 grid-rows-2 min-h-screen">
        <Map/>
        <ActionItems/>
        </div>
      </main>
    </div>
  )
}

export default Home
